# -*- coding: utf-8 -*-
"""semg-fatigue-analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16n_FguGEUd4NinfjRHdP8BZsNf0abvCt
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import butter, filtfilt

# Set random seed for reproducibility
np.random.seed(42)

# Parameters
fs = 2000          # Sampling rate (2000 Hz / samples per second)
duration = 15      # Contraction length in seconds
t = np.linspace(0, duration, int(fs * duration))

# 1. Create baseline Gaussian white noise
raw_noise = np.random.normal(0, 1, len(t))
semg_signal = np.zeros_like(raw_noise)

# 2. Simulate frequency drop (130 Hz down to 60 Hz) and amplitude increase over 500ms chunks
chunk_size = int(fs * 0.5)
for i in range(0, len(t), chunk_size):
    idx = slice(i, i + chunk_size)
    progress = i / len(t)  # Scale from 0 to 1

    current_freq = 130 - (130 - 60) * progress  # Frequency drops over time

    # Bandpass filter around the decaying frequency center
    low_cutoff = max(10, current_freq - 35)
    high_cutoff = min(fs/2 - 1, current_freq + 35)
    b, a = butter(4, [low_cutoff / (fs/2), high_cutoff / (fs/2)], btype='band')

    # Apply filter and increase amplitude slightly (motor unit synchronization)
    semg_signal[idx] = filtfilt(b, a, raw_noise[idx]) * (1 + 0.4 * progress)

print(f"✅ Step 1 Complete: Generated {duration} seconds of sEMG signal at {fs} Hz.")

from scipy.signal import iirnotch

def clean_emg_signal(signal, fs=2000):
    # 1. Bandpass Filter (20 Hz to 450 Hz)
    bp_b, bp_a = butter(4, [20 / (fs/2), 450 / (fs/2)], btype='bandpass')
    bandpassed = filtfilt(bp_b, bp_a, signal)

    # 2. Notch Filter (60 Hz Powerline Noise)
    notch_b, notch_a = iirnotch(w0=60 / (fs/2), Q=30.0)
    cleaned_signal = filtfilt(notch_b, notch_a, bandpassed)

    return cleaned_signal

clean_semg = clean_emg_signal(semg_signal, fs=fs)

print("✅ Step 2 Complete: Signal filtered between 20-450 Hz with 60 Hz powerline notch.")

from scipy.signal import welch

def extract_frequency_metrics(signal, fs=2000, window_sec=1.0, overlap_sec=0.5):
    win_len = int(window_sec * fs)
    step_len = int((window_sec - overlap_sec) * fs)

    time_points = []
    mdf_series = []
    mnf_series = []

    for start in range(0, len(signal) - win_len, step_len):
        segment = signal[start : start + win_len]

        # Calculate Power Spectral Density (PSD)
        freqs, psd = welch(segment, fs=fs, nperseg=min(512, len(segment)))

        # 1. Median Frequency (MDF)
        cum_power = np.cumsum(psd)
        total_power = cum_power[-1]
        mdf_idx = np.where(cum_power >= total_power / 2.0)[0][0]
        mdf_series.append(freqs[mdf_idx])

        # 2. Mean Frequency (MNF)
        mnf_val = np.sum(freqs * psd) / np.sum(psd)
        mnf_series.append(mnf_val)

        # Time stamp center of current window
        time_points.append((start + win_len / 2) / fs)

    return np.array(time_points), np.array(mdf_series), np.array(mnf_series)

time_stamps, mdf_values, mnf_values = extract_frequency_metrics(clean_semg, fs=fs)

print(f"✅ Step 3 Complete: Extracted {len(mdf_values)} windowed spectral metrics.")

from scipy.stats import linregress

# Linear regression for MDF
mdf_slope, mdf_intercept, mdf_r, _, _ = linregress(time_stamps, mdf_values)

# Linear regression for MNF
mnf_slope, mnf_intercept, mnf_r, _, _ = linregress(time_stamps, mnf_values)

print("--- FATIGUE ANALYSIS REPORT ---")
print(f"MDF Fatigue Rate: {mdf_slope:.3f} Hz/s  (R² = {mdf_r**2:.3f})")
print(f"MNF Fatigue Rate: {mnf_slope:.3f} Hz/s  (R² = {mnf_r**2:.3f})")

if mdf_slope < 0:
    print("STATUS: 🟢 Significant Muscle Fatigue Detected!")
else:
    print("STATUS: 🔴 No Muscle Fatigue Detected.")

plt.figure(figsize=(12, 8))

# Subplot 1: Cleaned Time-Domain sEMG Signal
plt.subplot(2, 1, 1)
plt.plot(t, clean_semg, color='teal', alpha=0.75, linewidth=0.8)
plt.title("Filtered Surface EMG Signal (Time Domain)", fontsize=13, fontweight='bold')
plt.xlabel("Time (seconds)")
plt.ylabel("Voltage (mV)")
plt.grid(True, linestyle='--', alpha=0.5)

# Subplot 2: Spectral Shift (MDF & MNF Decay Curves)
plt.subplot(2, 1, 2)
plt.scatter(time_stamps, mdf_values, color='firebrick', label='Measured MDF', zorder=3)
plt.plot(time_stamps, mdf_intercept + mdf_slope * time_stamps, 'r--',
         linewidth=2, label=f'MDF Slope: {mdf_slope:.2f} Hz/s (R²={mdf_r**2:.2f})')

plt.scatter(time_stamps, mnf_values, color='navy', label='Measured MNF', zorder=3)
plt.plot(time_stamps, mnf_intercept + mnf_slope * time_stamps, 'b--',
         linewidth=2, label=f'MNF Slope: {mnf_slope:.2f} Hz/s (R²={mnf_r**2:.2f})')

plt.title("Frequency Compression (Muscle Fatigue Metrics)", fontsize=13, fontweight='bold')
plt.xlabel("Time (seconds)")
plt.ylabel("Frequency (Hz)")
plt.legend(loc='upper right')
plt.grid(True, linestyle='--', alpha=0.5)

plt.tight_layout()
plt.show()